#include <Arduino.h>
#include <WiFi.h>
#include <WebServer.h>
#include <DNSServer.h>
#include <ArduinoOTA.h>
#include <Update.h>
#include <LittleFS.h>
#include <Preferences.h>
#include <time.h>
#include <esp_sntp.h>
#include <esp_sleep.h>
#include <driver/gpio.h>
#include <GxEPD2_BW.h>
#include "MarkdownParser.h"
#include "AppConfig.h"
#include "AppState.h"
#include "BmpRenderer.h"
#include "DeviceUi.h"
#include "OtaProgress.h"
#include "RefreshPolicy.h"
#include "RadioPolicy.h"
#include "StagedFileWriter.h"
#include "Secrets.h"
#include "TestAssets.h"
#include "WebUi.h"

// XIAO ESP32-C3 + 1.54in D67 (200x200). One active-low button on GPIO9.
#define BTN_PIN kButtonPin
GxEPD2_BW<GxEPD2_154_D67, GxEPD2_154_D67::HEIGHT> display(GxEPD2_154_D67(kDisplayCs,kDisplayDc,kDisplayReset,kDisplayBusy));
MarkdownParser md(&display); WebServer web(80); DNSServer dns; Preferences pref;
const char* ssid = kDefaultWifiSsid;
const char* password = kDefaultWifiPassword;
const char* AP_SSID="InkPocket-Setup";
const uint32_t MAX_PAYLOAD=kMaxApiPayload, MAX_BMP=kMaxBitmapBytes; const uint8_t MAX_BMPS=kMaxBitmapFiles;

DeviceSettings cfg;
RTC_DATA_ATTR int64_t rtcWakeEpochUs=0,rtcPlannedSleepUs=0; RTC_DATA_ATTR uint32_t rtcMagic=0,lastNtpAttemptHour=UINT32_MAX,lastNtpSuccessHour=UINT32_MAX; RTC_DATA_ATTR bool rtcSaverVisible=false; const uint32_t RTC_MAGIC=0x49504B32;
View view=HOME,backView=HOME; Radio radio=OFF; Remote remote=NONE;
bool focus=false,edit=false,dirty=true,saver=false,autoScroll=false,remoteTextMore=false,webOn=false,otaOn=false,wakeAfterRender=false,ntp=false,wifiPinned=false,radioBackground=false,resumeSleepAfterSync=false,credentialsPending=false,ignoreWakeButton=false,btnOld=false,longDone=false,uploadOk=false;
volatile bool ntpSynced=false;
uint8_t home=0,book=0,setting=0,partials=0,automaticPartials=0,books=0; uint16_t clicks=0,lastClockDay=65535;
uint32_t press=0,release=0,touched=0,lastScroll=0,joining=0,ntpAt=0,rebootAt=0,wifiApplyAt=0,lastMinute=UINT32_MAX,upSize=0,webTouched=0,toastUntil=0;
String files[32],opened,remotePath,saverPath,upTarget,upError,errorText,apPassword,toastText,pendingSsid,pendingPassword; int rx=0,ry=0,rw=200,rh=200,rscroll=0;
OtaProgressState ota;
RefreshPolicy refreshPolicy;
RadioPolicy radioPolicy;
StagedFileWriter stagedWriter;

bool ext(String s,const char* x){s.toLowerCase();String y=x;y.toLowerCase();return s.endsWith(y);}
String filename(String s){s.replace("\\","/");int p=s.lastIndexOf('/');if(p>=0)s=s.substring(p+1);String r;for(size_t i=0;i<s.length();i++){char c=s[i];if(isalnum(c)||c=='.'||c=='_'||c=='-')r+=c;}return r;}
String fsPath(String s){s.replace("\\","/");if(!s.startsWith("/"))s="/"+s;return s;}
bool pathOK(String p){return p.startsWith("/")&&p.indexOf("..")<0&&(ext(p,".md")||ext(p,".txt")||ext(p,".bmp"));}
String esc(String s){s.replace("\\","\\\\");s.replace("\"","\\\"");s.replace("\n","\\n");s.replace("\r","");return s;}
String randomApPassword(){char value[9];snprintf(value,sizeof(value),"%08lu",(unsigned long)(esp_random()%100000000UL));return String(value);}
String networkIp(){if(radio==PORTAL)return WiFi.softAPIP().toString();if(radio==ONLINE)return WiFi.localIP().toString();return "";}
DeviceUi::RadioMark radioMark(){if(radioBackground&&view!=HOME&&view!=WIFI)return DeviceUi::RadioMark::Off;if(radio==JOINING)return DeviceUi::RadioMark::On;if(radio==ONLINE)return DeviceUi::RadioMark::Client;if(radio==PORTAL)return DeviceUi::RadioMark::AccessPoint;return DeviceUi::RadioMark::Off;}
void error(String s){errorText=s;Serial.println("[error] "+s);dirty=true;}
void webActivity(){webTouched=millis();if(radio==ONLINE||radio==PORTAL)wifiPinned=true;}
void passiveWebActivity(){if(web.arg("passive")!="1")webActivity();}
void refreshRegion(int x,int y,int w,int h,bool automatic=false){refreshPolicy.region(x,y,w,h,automatic);dirty=true;}
void showToast(String text){toastText=text;toastUntil=0;refreshRegion(3,150,194,34);}
void toastLoop(){if(toastText.length()&&toastUntil&&(int32_t)(millis()-toastUntil)>=0){toastText="";toastUntil=0;refreshRegion(3,150,194,34);}}
void font(){DeviceUi::font(display);}
void wakeUI(){focus=true;saver=false;touched=millis();refreshPolicy.all();dirty=true;}
void loadCfg(){cfg.unfocus=constrain(pref.getUChar("unfocus",10),2,10);uint16_t st=pref.getUShort("saver_sec",30);cfg.saverSec=(st==15||st==30||st==60||st==120)?st:30;uint16_t h=pref.getUShort("hold",750);cfg.hold=(h==500||h==750||h==1000||h==1500)?h:750;cfg.fullAfter=constrain(pref.getUChar("partial",10),5,15);cfg.twelve=pref.getBool("twelve",false);cfg.saver=pref.getBool("saver",true);cfg.scrollSec=constrain(pref.getUChar("scroll",10),5,60);uint8_t sc=pref.getUChar("saver_clock",5);cfg.saverClockMin=(sc==0||sc==1||sc==5||sc==10)?sc:5;cfg.utc=constrain(pref.getShort("utc",330),-720,840);}
void saveCfg(){pref.putUChar("unfocus",cfg.unfocus);pref.putUShort("saver_sec",cfg.saverSec);pref.putUShort("hold",cfg.hold);pref.putUChar("partial",cfg.fullAfter);pref.putBool("twelve",cfg.twelve);pref.putBool("saver",cfg.saver);pref.putUChar("scroll",cfg.scrollSec);pref.putUChar("saver_clock",cfg.saverClockMin);pref.putShort("utc",cfg.utc);}
bool timeOK(){return time(nullptr)>1704067200;} time_t localEpoch(){return time(nullptr)+(time_t)cfg.utc*60;}
bool local(tm& o){if(!timeOK())return false;time_t n=localEpoch();gmtime_r(&n,&o);return true;} String two(int n){return n<10?"0"+String(n):String(n);}
String clockString(bool force24=false){tm n;if(!local(n))return "--:--";int h=n.tm_hour;String ap;if(cfg.twelve&&!force24){ap=h>=12?" PM":" AM";h%=12;if(!h)h=12;}return two(h)+":"+two(n.tm_min)+ap;}
String headerClockString(){tm n;if(!local(n))return "--:--";int h=n.tm_hour;if(cfg.twelve){h%=12;if(!h)h=12;}return two(h)+":"+two(n.tm_min);}
String dateString(){tm n;if(!local(n))return "Time not synced";char b[32];strftime(b,sizeof(b),"%a, %d %b %Y",&n);return b;}
String savedSsid(){return pref.getBool("wifi_custom",false)?pref.getString("ssid",ssid):String(ssid);}String savedPassword(){return pref.getBool("wifi_custom",false)?pref.getString("pass",password):String(password);}
void collectBooks(){books=0;File root=LittleFS.open("/");for(File f=root?root.openNextFile():File();f&&books<32;f=root.openNextFile()){if(!f.isDirectory()&&ext(f.name(),".md"))files[books++]=fsPath(f.name());f.close();}if(root)root.close();for(uint8_t i=0;i<books;i++)for(uint8_t j=i+1;j<books;j++)if(files[j]<files[i]){String t=files[i];files[i]=files[j];files[j]=t;}if(book>=books)book=0;}
bool writeBundledFile(const char* path,const uint8_t* bytes,size_t length){File f=LittleFS.open(path,"w");if(!f)return false;size_t written=f.write(bytes,length);f.close();return written==length;}
void ensureExamples(){bool refreshBmp=pref.getUChar("asset_ver",0)<kBundledAssetVersion;if(refreshBmp||!LittleFS.exists("/test.bmp")){if(writeBundledFile("/test.bmp",kTestBmp,kTestBmpSize))pref.putUChar("asset_ver",kBundledAssetVersion);else error("Could not add test.bmp");}if(!LittleFS.exists("/EReader.md")){File f=LittleFS.open("/EReader.md","w");if(!f||!f.print(kExampleMarkdown)){if(f)f.close();error("Could not add EReader.md");return;}f.close();}}
void recoverStagedFiles(){LittleFS.remove("/.up.tmp");LittleFS.remove("/.api.tmp");LittleFS.remove("/.api.txt.tmp");LittleFS.remove("/.api.md.tmp");LittleFS.remove("/.api.bmp.tmp");File root=LittleFS.open("/");for(File f=root?root.openNextFile():File();f;f=root.openNextFile()){String name=fsPath(f.name());f.close();if(!name.endsWith(".bak"))continue;String target=name.substring(0,name.length()-4);if(pathOK(target)||target.startsWith("/.api.")){if(LittleFS.exists(target))LittleFS.remove(name);else LittleFS.rename(name,target);}}if(root)root.close();}
uint8_t bmpCount(){uint8_t n=0;File r=LittleFS.open("/");for(File f=r?r.openNextFile():File();f;f=r.openNextFile()){if(!f.isDirectory()&&ext(f.name(),".bmp"))n++;f.close();}if(r)r.close();return n;}
String cut(String s,uint8_t n){if(s.startsWith("/"))s.remove(0,1);return s.length()>n?s.substring(0,n-3)+"...":s;}
void centred(String s,int y,uint8_t size=1){DeviceUi::centered(display,s,y,size);}

void header(String s){DeviceUi::header(display,s,radioMark(),radio==ONLINE?WiFi.RSSI():0);}
void tile(int n,int x,int y,String label){DeviceUi::tile(display,n,x,y,label,focus&&home==n);}
void showHome(){DeviceUi::homeHeader(display,"InkPocket",headerClockString(),radioMark(),radio==ONLINE?WiFi.RSSI():0);tile(0,7,30,"Reader");tile(1,103,30,"Clock");tile(2,7,113,"API");tile(3,103,113,"Settings");}
void showList(){header("READER");if(!books){centred("No Markdown files",76);centred("Upload .md in Wi-Fi mode",94);return;}int start=book>=6?book-5:0;for(int i=0;i<6&&start+i<books;i++){int item=start+i,y=28+i*27;bool on=focus&&item==book;if(on){display.fillRoundRect(5,y,190,22,4,GxEPD_BLACK);display.setTextColor(GxEPD_WHITE);}else display.drawRoundRect(5,y,190,22,4,GxEPD_BLACK);display.setCursor(11,y+7);display.print(cut(files[item],26));font();}}
void showMd(String p,bool top=false){md.setTopOffset(top?20:0);md.resetForRender();File f=LittleFS.open(p,"r");if(!f){display.setCursor(10,50);display.print("Cannot open document.");md.setMoreContent(false);return;}while(f.available()){String l=f.readStringUntil('\n');l.replace("\r","");md.parseBlock(l);if(md.pastViewport())break;}md.setMoreContent(f.available());f.close();}
void showClock(){tm n;if(!local(n)){DeviceUi::clockApp(display,focus,false,"","","","","","","","",cfg.unfocus,radioMark(),radio==ONLINE?WiFi.RSSI():0);return;}lastClockDay=n.tm_yday;int hour=n.tm_hour;String meridiem;if(cfg.twelve){meridiem=hour>=12?"PM":"AM";hour%=12;if(!hour)hour=12;}char dayText[8],monthText[8],yearText[6];strftime(dayText,sizeof(dayText),"%a",&n);strftime(monthText,sizeof(monthText),"%b",&n);strftime(yearText,sizeof(yearText),"%Y",&n);String day=dayText,month=monthText;day.toUpperCase();month.toUpperCase();DeviceUi::clockApp(display,focus,true,two(hour),two(n.tm_min),meridiem,day,two(n.tm_mday),month,yearText,dateString(),cfg.unfocus,radioMark(),radio==ONLINE?WiFi.RSSI():0);}
bool monoBmp(String p){return MonoBmp::valid(LittleFS,p);}
bool showBmp(String p,int dx,int dy,int dw,int dh){return MonoBmp::draw(LittleFS,display,p,dx,dy,dw,dh);}
void showText(){File f=LittleFS.open(remotePath,"r");if(!f){display.print("No API content");remoteTextMore=false;return;}font();int x=rx,y=ry+10-rscroll;remoteTextMore=false;while(f.available()){String line=f.readStringUntil('\n');for(size_t i=0;i<line.length();i++){if(line[i]=='\n')continue;if(x>rx+rw-6){x=rx;y+=10;}if(y>ry-10&&y<ry+rh+10){display.setCursor(x,y);display.print(line[i]);}x+=6;}x=rx;y+=10;if(y>ry+rh+220){remoteTextMore=f.available();break;}}f.close();}
void showApi(){if(remote==TEXT){showText();return;}if(remote==MARKDOWN){showMd(remotePath);return;}if(remote==BITMAP){if(!showBmp(remotePath,rx,ry,rw,rh))error("API BMP invalid");return;}header("API CONTROL");centred("Remote Display",65,2);centred("POST text, Markdown or BMP",96);centred(radio==ONLINE?WiFi.localIP().toString():"Enable Wi-Fi from Home",125);centred("Hold: home",191);}
const char* setName(uint8_t n){static const char* a[]={"Unfocus timeout","Saver timeout","Saver clock","Long press","Full refresh","12-hour clock","Screen saver","Auto-scroll","UTC offset","Sync time now","Wi-Fi mode"};return a[n];}
String setVal(uint8_t n){if(n==0)return String(cfg.unfocus)+" sec";if(n==1)return String(cfg.saverSec)+" sec";if(n==2)return cfg.saverClockMin?String(cfg.saverClockMin)+" min":"Off";if(n==3)return String(cfg.hold)+" ms";if(n==4)return String(cfg.fullAfter)+" partials";if(n==5)return cfg.twelve?"12 hour":"24 hour";if(n==6)return cfg.saver?"On":"Off";if(n==7)return String(cfg.scrollSec)+" sec";if(n==8){char b[14];snprintf(b,sizeof(b),"UTC%+d:%02d",cfg.utc/60,abs(cfg.utc%60));return b;}if(n==9)return radio==ONLINE?"Run":"Connect";if(radio==JOINING)return "Connecting";if(radio==ONLINE)return "Client";if(radio==PORTAL)return "Setup AP";return "Start";}
void showSettings(){header(edit?"EDIT SETTING":"SETTINGS");int start=setting>=5?setting-4:0;for(int i=0;i<5&&start+i<11;i++){int n=start+i,y=28+i*32;bool on=focus&&n==setting;if(on){display.fillRoundRect(4,y,192,28,4,GxEPD_BLACK);display.setTextColor(GxEPD_WHITE);}else display.drawRoundRect(4,y,192,28,4,GxEPD_BLACK);display.setCursor(10,y+5);display.print(setName(n));display.setCursor(10,y+16);display.print(setVal(n));font();}}
void chooseSaver(){String a[MAX_BMPS];uint8_t n=0;File r=LittleFS.open("/");for(File f=r?r.openNextFile():File();f&&n<MAX_BMPS;f=r.openNextFile()){if(!f.isDirectory()&&ext(f.name(),".bmp"))a[n++]=fsPath(f.name());f.close();}if(r)r.close();saverPath=n?a[esp_random()%n]:"";}
void showSaver(){if(saverPath.length())showBmp(saverPath,0,0,200,200);if(cfg.saverClockMin){String v=clockString(true);const int x=130,y=172,w=65,h=23;display.fillRoundRect(x,y,w,h,6,GxEPD_WHITE);display.drawRoundRect(x,y,w,h,6,GxEPD_BLACK);DeviceUi::faceInRect(display,v,&FreeMonoBold9pt7b,x+4,y+2,w-8,h-4);}}
void showOtaProgress(){header("InkPocket update");uint8_t percent=ota.percent();centred(ota.message.length()?ota.message:"Writing firmware",56);String amount=ota.total?String(percent)+"%":String(ota.written/1024)+" KB";DeviceUi::faceInRect(display,amount,ota.total?&FreeMonoBold24pt7b:&FreeMonoBold9pt7b,10,68,180,42);display.drawRoundRect(14,116,172,20,4,GxEPD_BLACK);if(ota.total&&percent){int width=(168*percent)/100;display.fillRoundRect(16,118,width,16,2,GxEPD_BLACK);}if(ota.total)centred(String(ota.written/1024)+" / "+String(ota.total/1024)+" KB",151);else centred("Receiving firmware",151);centred("Keep power connected",174);}
void renderOta(bool immediate=false){uint8_t step=ota.displayStep();if(!immediate&&ota.screenReady&&step==ota.shownStep&&millis()-ota.lastDraw<1500)return;if(ota.screenReady)display.setPartialWindow(0,0,200,200);else display.setFullWindow();display.firstPage();do{display.fillScreen(GxEPD_WHITE);showOtaProgress();}while(display.nextPage());ota.screenReady=true;ota.shownStep=step;ota.lastDraw=millis();dirty=false;}
void beginOtaProgress(uint32_t total){ota.begin(total);saver=false;focus=false;touched=millis();renderOta(true);}
void updateOtaProgress(uint32_t written,uint32_t total=0){ota.written=written;if(total)ota.total=total;ota.lastActivity=millis();ota.message="Writing firmware";renderOta(false);}
void finishOtaProgress(){if(!ota.total)ota.total=ota.written;ota.written=max(ota.written,ota.total);ota.ok=true;ota.verified=true;ota.lastActivity=millis();ota.message="Firmware verified";pref.putBool("ota_resume",true);rebootAt=millis()+2500;renderOta(true);}
void failOtaProgress(String message){ota.ok=false;ota.verified=false;ota.lastActivity=millis();ota.message=message;renderOta(true);ota.active=false;touched=millis();}
void otaLoop(){if(ota.active&&!ota.verified&&millis()-ota.lastActivity>45000){Update.abort();failOtaProgress("Update timed out");}}
String activeSsid(){return credentialsPending?pendingSsid:savedSsid();}
void showWifi(){DeviceUi::wifiApp(display,radioMark(),radio==PORTAL?String(AP_SSID):activeSsid(),networkIp(),apPassword,radio==ONLINE?WiFi.RSSI():0);}
void render(bool force=false){if(ota.active){renderOta(force);return;}bool armToast=toastText.length()&&!toastUntil;bool autoFull=refreshPolicy.automatic&&automaticPartials>=60;bool all=force||autoFull||(!refreshPolicy.automatic&&partials>=cfg.fullAfter);if(all){display.setFullWindow();partials=0;automaticPartials=0;}else if(refreshPolicy.regional){display.setPartialWindow(refreshPolicy.x,refreshPolicy.y,refreshPolicy.width(),refreshPolicy.height());if(refreshPolicy.automatic)automaticPartials++;else partials++;}else{display.setPartialWindow(0,0,200,200);partials++;}display.firstPage();do{display.fillScreen(GxEPD_WHITE);if(saver)showSaver();else if(view==HOME)showHome();else if(view==LIST)showList();else if(view==BOOK)showMd(opened);else if(view==CLOCK)showClock();else if(view==API)showApi();else if(view==SETTINGS)showSettings();else showWifi();if(errorText.length()&&!saver&&view!=WIFI){String e=errorText.length()>30?errorText.substring(0,27)+"...":errorText;display.fillRoundRect(3,158,194,19,3,GxEPD_WHITE);display.drawRoundRect(3,158,194,19,3,GxEPD_BLACK);display.setCursor(7,164);display.print("! "+e);}if(toastText.length()&&!saver)DeviceUi::toast(display,toastText);}while(display.nextPage());if(armToast)toastUntil=millis()+1000;dirty=false;refreshPolicy.all();}

void startWeb(){webTouched=millis();if(!webOn){web.begin();webOn=true;}if(!otaOn){ArduinoOTA.setHostname("inkpocket");ArduinoOTA.onStart([](){webActivity();beginOtaProgress(0);ota.ok=true;ota.message="Receiving Arduino OTA";renderOta(true);});ArduinoOTA.onProgress([](unsigned int progress,unsigned int total){webActivity();updateOtaProgress(progress,total);});ArduinoOTA.onEnd([](){finishOtaProgress();});ArduinoOTA.onError([](ota_error_t){failOtaProgress("Arduino OTA failed");});ArduinoOTA.begin();otaOn=true;}}
void stopWeb(){if(otaOn){ArduinoOTA.end();otaOn=false;}if(webOn){web.stop();webOn=false;}}
void radioVisualChanged(){if(saver)return;if(view==HOME)refreshRegion(0,0,200,23);else if(view==WIFI){refreshPolicy.all();dirty=true;}}
void timeVisualChanged(){if(saver&&cfg.saverClockMin)refreshRegion(126,168,72,30,true);else if(view==HOME)refreshRegion(0,0,200,23,true);else if(view==CLOCK){refreshPolicy.all();dirty=true;}}
uint32_t localHour(){return timeOK()?(uint32_t)(localEpoch()/3600):UINT32_MAX;}
uint32_t secondsToNextLocalHour(){if(!timeOK())return UINT32_MAX;uint32_t past=(uint32_t)localEpoch()%3600;return past?3600-past:3600;}
bool hourlySyncDue(){uint32_t hour=localHour();return hour!=UINT32_MAX&&hour!=lastNtpAttemptHour;}
void markNtpAttempt(){lastNtpAttemptHour=localHour();}
void ntpSyncComplete(struct timeval*){ntpSynced=true;}
void startPortal(){radioPolicy.purpose=RadioPurpose::Setup;radioBackground=false;resumeSleepAfterSync=false;if(view!=WIFI)backView=view;view=WIFI;dns.stop();stopWeb();WiFi.disconnect(false);WiFi.mode(WIFI_AP);apPassword=randomApPassword();WiFi.softAP(AP_SSID,apPassword.c_str());dns.start(53,"*",WiFi.softAPIP());radio=PORTAL;startWeb();errorText="";Serial.println("[wifi] Setup AP ready at "+WiFi.softAPIP().toString());refreshPolicy.all();dirty=true;}
void startWifi(bool keep,bool background=false,bool usePending=false){toastText="";toastUntil=0;wifiPinned=keep;radioBackground=background;radioPolicy.purpose=background?RadioPurpose::TimeSync:RadioPurpose::Web;if(!background){backView=view;view=WIFI;}String network=usePending?pendingSsid:savedSsid();String networkPassword=usePending?pendingPassword:savedPassword();if(!network.length()){if(background){bool resume=resumeSleepAfterSync;radioBackground=false;resumeSleepAfterSync=false;radioPolicy.purpose=RadioPurpose::None;if(resume)wakeAfterRender=true;return;}startPortal();return;}stopWeb();WiFi.mode(WIFI_STA);WiFi.setSleep(true);WiFi.begin(network.c_str(),networkPassword.c_str());radio=JOINING;joining=millis();radioVisualChanged();}
void stopWifi(bool notify=true){bool wasOn=radio!=OFF;dns.stop();stopWeb();WiFi.softAPdisconnect(true);WiFi.disconnect(false);WiFi.mode(WIFI_OFF);radio=OFF;wifiPinned=false;radioBackground=false;radioPolicy.purpose=RadioPurpose::None;radioVisualChanged();if(wasOn&&notify)showToast("Radio Off");}
void startNtp(){if(radio==ONLINE){markNtpAttempt();ntpSynced=false;sntp_stop();sntp_set_sync_mode(SNTP_SYNC_MODE_IMMED);sntp_set_time_sync_notification_cb(ntpSyncComplete);configTime(0,0,"pool.ntp.org","time.nist.gov","time.google.com");ntp=true;ntpAt=millis();}}
void beginHourlySync(bool resumeSleep){markNtpAttempt();resumeSleepAfterSync=resumeSleep;startWifi(false,true);}
void finishBackgroundSync(bool synced){bool resume=resumeSleepAfterSync;resumeSleepAfterSync=false;stopWifi(false);if(synced)timeVisualChanged();if(resume)wakeAfterRender=true;}
void radioLoop(){if(radio==PORTAL)dns.processNextRequest();if(radio==ONLINE&&WiFi.status()!=WL_CONNECTED&&!ota.active){radio=JOINING;joining=millis();WiFi.reconnect();radioVisualChanged();}if(radio==JOINING){if(WiFi.status()==WL_CONNECTED){radio=ONLINE;if(credentialsPending){pref.putString("ssid",pendingSsid);pref.putString("pass",pendingPassword);pref.putBool("wifi_custom",true);credentialsPending=false;pendingSsid="";pendingPassword="";showToast("Wi-Fi saved");}if(radioBackground)startNtp();else{startWeb();startNtp();}errorText="";radioVisualChanged();}else{uint32_t limit=radioBackground?RadioPolicy::kBackgroundJoinMs:RadioPolicy::kManualJoinMs;if(millis()-joining>limit){if(radioBackground)finishBackgroundSync(false);else{if(credentialsPending){credentialsPending=false;pendingSsid="";pendingPassword="";showToast("Previous Wi-Fi kept");}startPortal();}}}}if(radio==ONLINE&&otaOn)ArduinoOTA.handle();if(ntp&&radio==ONLINE){if(ntpSynced){ntp=false;ntpSynced=false;lastNtpSuccessHour=localHour();if(radioBackground)finishBackgroundSync(true);else if(!wifiPinned){View prior=backView;stopWifi();view=prior;refreshPolicy.all();dirty=true;}else timeVisualChanged();}else if(millis()-ntpAt>RadioPolicy::kNtpTimeoutMs){ntp=false;if(radioBackground)finishBackgroundSync(false);else{error("NTP sync failed");if(!wifiPinned){View prior=backView;stopWifi();view=prior;refreshPolicy.all();dirty=true;}}}}if((radio==ONLINE||radio==PORTAL)&&!ota.active){uint32_t limit=radio==PORTAL?RadioPolicy::kSetupIdleMs:RadioPolicy::kWebIdleMs;if(millis()-webTouched>=limit){bool wifiView=view==WIFI;stopWifi();resumeSleepAfterSync=false;if(wifiView)view=backView;refreshPolicy.all();dirty=true;}}}

String filesJson(){String s="{\"files\":[";bool first=true;File r=LittleFS.open("/");for(File f=r?r.openNextFile():File();f;f=r.openNextFile()){String n=fsPath(f.name());if(!f.isDirectory()&&pathOK(n)){if(!first)s+=",";s+="{\"name\":\""+esc(n)+"\",\"size\":"+String(f.size())+"}";first=false;}f.close();}if(r)r.close();return s+"],\"used\":"+String(LittleFS.usedBytes())+",\"total\":"+String(LittleFS.totalBytes())+"}";}
String status(){const char* v=view==HOME?"home":view==LIST?"reader-list":view==BOOK?"reader":view==CLOCK?"clock":view==API?"api":view==SETTINGS?"settings":"wifi";const char*r=radio==ONLINE?"connected":radio==JOINING?"connecting":radio==PORTAL?"portal":"off";long next=timeOK()?(long)secondsToNextLocalHour():-1;return "{\"device\":\"InkPocket\",\"app\":\""+String(v)+"\",\"wifi\":\""+r+"\",\"ip\":\""+networkIp()+"\",\"rssi\":"+String(radio==ONLINE?WiFi.RSSI():0)+",\"time\":\""+clockString()+"\",\"time_valid\":"+String(timeOK()?"true":"false")+",\"ntp_next_sync_sec\":"+String(next)+",\"ntp_last_success_hour\":"+String(lastNtpSuccessHour)+",\"free_heap\":"+String(ESP.getFreeHeap())+",\"max_payload\":"+String(MAX_PAYLOAD)+"}";}
void mediaUpload(){webActivity();HTTPUpload&u=web.upload();if(u.status==UPLOAD_FILE_START){uploadOk=false;upError="";upSize=0;String n=filename(u.filename);upTarget="/"+n;bool b=ext(n,".bmp");if(!n.length()||!(ext(n,".md")||ext(n,".txt")||b))upError="Only .md, .txt, and BMP files are allowed.";else if(b&&!LittleFS.exists(upTarget)&&bmpCount()>=MAX_BMPS)upError="Five BMP files already exist.";else{uint32_t freeBytes=LittleFS.totalBytes()>LittleFS.usedBytes()+1024?LittleFS.totalBytes()-LittleFS.usedBytes()-1024:0;uploadOk=stagedWriter.begin(LittleFS,upTarget,"/.up.tmp",b?MAX_BMP:MAX_PAYLOAD,freeBytes);if(!uploadOk)upError=stagedWriter.error();}}else if(u.status==UPLOAD_FILE_WRITE&&uploadOk){uploadOk=stagedWriter.write(u.buf,u.currentSize);upSize=stagedWriter.size();if(!uploadOk)upError=stagedWriter.error();}else if(u.status==UPLOAD_FILE_END&&uploadOk){uploadOk=stagedWriter.finishInput();if(uploadOk&&ext(upTarget,".bmp")&&!monoBmp(stagedWriter.inputPath())){uploadOk=false;upError="BMP must be uncompressed 1-bit.";stagedWriter.abort();}else if(uploadOk){uploadOk=stagedWriter.commit();if(!uploadOk)upError=stagedWriter.error();}else upError=stagedWriter.error();if(uploadOk)collectBooks();}else if(u.status==UPLOAD_FILE_ABORTED){stagedWriter.abort();uploadOk=false;upError="Upload cancelled.";}}
void remoteUpload(Remote kind){webActivity();bool multipart=web.header("Content-Type").startsWith("multipart/");HTTPUploadStatus status=UPLOAD_FILE_ABORTED;const uint8_t* data=nullptr;size_t length=0;if(multipart){HTTPUpload&u=web.upload();status=u.status;data=u.buf;length=u.currentSize;}else{HTTPRaw&r=web.raw();status=r.status==RAW_START?UPLOAD_FILE_START:r.status==RAW_WRITE?UPLOAD_FILE_WRITE:r.status==RAW_END?UPLOAD_FILE_END:UPLOAD_FILE_ABORTED;data=r.buf;length=r.currentSize;}String target=kind==TEXT?"/.api.txt":kind==MARKDOWN?"/.api.md":"/.api.bmp";String temporary=target+".tmp";if(status==UPLOAD_FILE_START){uploadOk=multipart||web.clientContentLength()<=MAX_PAYLOAD;upError=uploadOk?"":"Payload too large.";upSize=0;if(uploadOk){uint32_t freeBytes=LittleFS.totalBytes()>LittleFS.usedBytes()+1024?LittleFS.totalBytes()-LittleFS.usedBytes()-1024:0;uploadOk=stagedWriter.begin(LittleFS,target,temporary,MAX_PAYLOAD,freeBytes);if(!uploadOk)upError=stagedWriter.error();}}else if(status==UPLOAD_FILE_WRITE&&uploadOk){uploadOk=stagedWriter.write(data,length);upSize=stagedWriter.size();if(!uploadOk)upError=stagedWriter.error();}else if(status==UPLOAD_FILE_END&&uploadOk){uploadOk=stagedWriter.finishInput();if(uploadOk&&kind==BITMAP&&!monoBmp(stagedWriter.inputPath())){uploadOk=false;upError="BMP must be uncompressed 1-bit.";stagedWriter.abort();}else if(uploadOk){uploadOk=stagedWriter.commit();if(!uploadOk)upError=stagedWriter.error();}else upError=stagedWriter.error();}else if(status==UPLOAD_FILE_ABORTED){stagedWriter.abort();uploadOk=false;upError="Upload cancelled.";}}
void otaUpload(){webActivity();HTTPUpload&u=web.upload();if(u.status==UPLOAD_FILE_START){uint32_t total=web.hasArg("size")?(uint32_t)strtoul(web.arg("size").c_str(),nullptr,10):0;beginOtaProgress(total);ota.ok=Update.begin(UPDATE_SIZE_UNKNOWN,U_FLASH);if(ota.ok){ota.message="Writing firmware";renderOta(true);}else failOtaProgress("Cannot start update");}else if(u.status==UPLOAD_FILE_WRITE&&ota.ok){size_t written=Update.write(u.buf,u.currentSize);ota.written+=written;if(written!=u.currentSize)failOtaProgress("Firmware write failed");else updateOtaProgress(ota.written);}else if(u.status==UPLOAD_FILE_END&&ota.ok){ota.message="Verifying firmware";renderOta(true);ota.ok=Update.end(true);if(ota.ok)finishOtaProgress();else failOtaProgress("Verification failed");}else if(u.status==UPLOAD_FILE_ABORTED){Update.abort();failOtaProgress("Transfer cancelled");}}
void remoteView(){saver=false;view=API;focus=false;touched=millis();dirty=true;}
String controlHeader(const char*n){if(!strcmp(n,"x"))return web.header("X-InkPocket-X");if(!strcmp(n,"y"))return web.header("X-InkPocket-Y");if(!strcmp(n,"w"))return web.header("X-InkPocket-W");if(!strcmp(n,"h"))return web.header("X-InkPocket-H");return "";}
int coord(const char*n,int d,int hi){String value=web.hasArg(n)?web.arg(n):controlHeader(n);return value.length()?constrain(value.toInt(),0,hi):d;}
bool requestedAutoScroll(){return web.arg("scroll")=="auto"||web.header("X-InkPocket-Scroll")=="auto";}
void routes(){
 const char* headers[]={"Content-Type","X-InkPocket-X","X-InkPocket-Y","X-InkPocket-W","X-InkPocket-H","X-InkPocket-Scroll"};web.collectHeaders(headers,6);
 web.on("/",HTTP_GET,[](){webActivity();web.send_P(200,"text/html",kWebPage);});web.on("/api/files",HTTP_GET,[](){passiveWebActivity();web.send(200,"application/json",filesJson());});
 web.on("/api/files/download",HTTP_GET,[](){webActivity();String p=web.arg("path");if(!pathOK(p)||!LittleFS.exists(p)){web.send(404,"text/plain","File not found.");return;}File f=LittleFS.open(p,"r");if(!f){web.send(500,"text/plain","Could not open file.");return;}String type=ext(p,".bmp")?"image/bmp":ext(p,".md")?"text/markdown; charset=utf-8":"text/plain; charset=utf-8";web.sendHeader("Content-Disposition","inline; filename=\""+filename(p)+"\"");web.streamFile(f,type);f.close();});
 web.on("/api/files/delete",HTTP_POST,[](){webActivity();String p=web.arg("path");if(!pathOK(p)||!LittleFS.exists(p)){web.send(400,"text/plain","Invalid file.");return;}LittleFS.remove(p);collectBooks();web.send(200,"text/plain","Deleted.");});
 web.on("/api/files/upload",HTTP_POST,[](){webActivity();web.send(uploadOk?200:507,"text/plain",uploadOk?"Upload complete.":upError);},mediaUpload);
 web.on("/api/wifi",HTTP_POST,[](){webActivity();String s=web.arg("ssid"),p=web.arg("password");if(!s.length()||s.length()>32||p.length()>63){web.send(400,"text/plain","Invalid Wi-Fi credentials.");return;}pendingSsid=s;pendingPassword=p;credentialsPending=true;web.send(202,"text/plain","Testing connection. Existing Wi-Fi is kept until this succeeds...");wifiApplyAt=millis()+500;});
 web.on("/api/ota",HTTP_POST,[](){webActivity();if(!ota.ok||!ota.verified){web.send(500,"text/plain","OTA failed.");return;}web.send(200,"text/plain","Firmware installed. Restarting...");},otaUpload);
 web.on("/api/v1/status",HTTP_GET,[](){passiveWebActivity();web.send(200,"application/json",status());});web.on("/api/v1/time/sync",HTTP_POST,[](){webActivity();if(radio==ONLINE)startNtp();else startWifi(false);web.send(202,"application/json","{\"status\":\"syncing\"}");});
 web.on("/api/v1/app",HTTP_POST,[](){webActivity();touched=millis();saver=false;String a=web.arg("name");a.toLowerCase();remote=NONE;if(a=="home"||a=="menu"){view=HOME;focus=false;}else if(a=="reader"){collectBooks();view=LIST;focus=true;}else if(a=="clock"){view=CLOCK;focus=false;}else if(a=="settings"){view=SETTINGS;focus=true;}else{view=API;focus=false;}dirty=true;web.send(200,"application/json","{\"status\":\"ok\"}");});
 web.on("/api/v1/screen/clear",HTTP_POST,[](){webActivity();remote=NONE;remoteView();web.send(200,"application/json","{\"status\":\"cleared\"}");});
 web.on("/api/v1/screen/text",HTTP_POST,[](){webActivity();if(!uploadOk){web.send(upError=="Payload too large."?413:507,"text/plain",upError);return;}remotePath="/.api.txt";remote=TEXT;rscroll=0;remoteTextMore=true;autoScroll=requestedAutoScroll();lastScroll=millis();rx=coord("x",0,199);ry=coord("y",0,199);int requestedW=coord("w",200,200),requestedH=coord("h",200,200);rw=constrain(requestedW,1,200-rx);rh=constrain(requestedH,1,200-ry);remoteView();web.send(200,"application/json","{\"status\":\"shown\"}");},[](){remoteUpload(TEXT);});
 web.on("/api/v1/screen/markdown",HTTP_POST,[](){webActivity();if(!uploadOk){web.send(upError=="Payload too large."?413:507,"text/plain",upError);return;}md.resetScroll();remotePath="/.api.md";remote=MARKDOWN;autoScroll=requestedAutoScroll();lastScroll=millis();remoteView();web.send(200,"application/json","{\"status\":\"shown\"}");},[](){remoteUpload(MARKDOWN);});
 web.on("/api/v1/screen/bmp",HTTP_POST,[](){webActivity();if(!uploadOk){web.send(400,"text/plain",upError);return;}remotePath="/.api.bmp";remote=BITMAP;rx=coord("x",0,199);ry=coord("y",0,199);int requestedW=coord("w",200,200),requestedH=coord("h",200,200);rw=constrain(requestedW,1,200-rx);rh=constrain(requestedH,1,200-ry);remoteView();web.send(200,"application/json","{\"status\":\"shown\"}");},[](){remoteUpload(BITMAP);});
 web.onNotFound([](){webActivity();if(radio==PORTAL){web.sendHeader("Location","http://192.168.4.1/",true);web.send(302,"text/plain","");}else web.send(404,"text/plain","Not found");});
}

void changeSetting(){if(setting==0)cfg.unfocus=cfg.unfocus>=10?2:cfg.unfocus+1;else if(setting==1)cfg.saverSec=cfg.saverSec<30?30:cfg.saverSec<60?60:cfg.saverSec<120?120:15;else if(setting==2)cfg.saverClockMin=cfg.saverClockMin==0?1:cfg.saverClockMin==1?5:cfg.saverClockMin==5?10:0;else if(setting==3){const uint16_t x[]={500,750,1000,1500};uint8_t n=0;while(n<3&&x[n]!=cfg.hold)n++;cfg.hold=x[(n+1)%4];}else if(setting==4)cfg.fullAfter=cfg.fullAfter>=15?5:cfg.fullAfter+1;else if(setting==5)cfg.twelve=!cfg.twelve;else if(setting==6)cfg.saver=!cfg.saver;else if(setting==7)cfg.scrollSec=cfg.scrollSec>=60?5:cfg.scrollSec+5;else if(setting==8){cfg.utc+=30;if(cfg.utc>840)cfg.utc=-720;}}
bool dismissSaver(){if(!saver)return false;saver=false;rtcSaverVisible=false;view=HOME;focus=false;dirty=true;touched=millis();return true;}
void single(){if(dismissSaver())return;if(!focus){wakeUI();return;}wakeUI();if(view==HOME)home=(home+1)%4;else if(view==LIST&&books)book=(book+1)%books;else if(view==BOOK){md.scrollDown(160);autoScroll=false;}else if(view==API){if(remote==MARKDOWN)md.scrollDown(160);else if(remote==TEXT&&remoteTextMore)rscroll+=160;autoScroll=false;}else if(view==SETTINGS){if(edit)changeSetting();else setting=(setting+1)%11;}}
void doubleClick(){if(dismissSaver())return;if(!focus){wakeUI();return;}wakeUI();if(view==HOME){if(home==0){collectBooks();view=LIST;focus=true;}else if(home==1)view=CLOCK;else if(home==2){remote=NONE;view=API;}else view=SETTINGS;}else if(view==LIST&&books){opened=files[book];md.resetScroll();view=BOOK;}else if(view==BOOK){md.scrollUp(160);autoScroll=false;}else if(view==API){if(remote==MARKDOWN)md.scrollUp(160);else if(remote==TEXT)rscroll=max(0,rscroll-160);autoScroll=false;}else if(view==SETTINGS){if(edit){saveCfg();edit=false;}else if(setting<=8)edit=true;else if(setting==9){if(radio==ONLINE)startNtp();else startWifi(false);}else{if(radio==OFF){backView=SETTINGS;startWifi(true);view=WIFI;}else stopWifi();}}}
void triple(){if(dismissSaver())return;if(!focus){wakeUI();return;}if(view==BOOK||(view==API&&(remote==TEXT||remote==MARKDOWN))){autoScroll=!autoScroll;lastScroll=millis();wakeUI();showToast(autoScroll?"Auto-scroll on":"Auto-scroll off");}}
void goBack(){autoScroll=false;edit=false;saver=false;if(view==BOOK){view=LIST;focus=true;}else if(view==LIST||view==CLOCK||view==API||view==SETTINGS){view=HOME;focus=true;}else if(view==WIFI){stopWifi();view=backView;focus=true;}dirty=true;touched=millis();}
void buttonLoop(){bool down=digitalRead(BTN_PIN)==LOW;uint32_t now=millis();if(ota.active){if(down&&!btnOld){press=now;longDone=false;}if(down&&!longDone&&!ota.verified&&now-press>=5000){Update.abort();failOtaProgress("Update cancelled");longDone=true;}btnOld=down;return;}if(ignoreWakeButton){if(!down){ignoreWakeButton=false;btnOld=false;clicks=0;}else btnOld=true;return;}if(down&&!btnOld){press=now;longDone=false;}uint32_t limit=view==HOME?5000:cfg.hold;if(down&&!longDone&&now-press>=limit){if(!focus&&view!=HOME)wakeUI();else if(view==HOME){startWifi(true);dirty=true;}else goBack();longDone=true;clicks=0;}if(!down&&btnOld){release=now;if(!longDone&&now-press>=35)clicks++;}if(!down&&clicks&&now-release>340){uint16_t n=clicks;clicks=0;if(n==1)single();else if(n==2)doubleClick();else if(n==3)triple();}btnOld=down;}
uint32_t untilBoundary(uint32_t interval){if(!timeOK()||!interval)return UINT32_MAX;uint32_t past=(uint32_t)localEpoch()%interval;return past?interval-past:interval;}
void waitForButtonRelease(){if(digitalRead(BTN_PIN)!=LOW)return;display.hibernate();do{esp_sleep_disable_wakeup_source(ESP_SLEEP_WAKEUP_ALL);esp_sleep_enable_timer_wakeup(2000000ULL);esp_light_sleep_start();}while(digitalRead(BTN_PIN)==LOW);display.init(115200,false,2,false);ignoreWakeButton=false;btnOld=false;clicks=0;}
void sleepNow(bool timedRefresh){bool clockSleep=view==CLOCK&&!focus&&!saver;waitForButtonRelease();uint32_t displaySec=UINT32_MAX;if(timedRefresh){uint32_t step=clockSleep?60UL:(saver&&cfg.saverClockMin?(uint32_t)cfg.saverClockMin*60UL:0);displaySec=untilBoundary(step);}uint32_t ntpSec=secondsToNextLocalHour();uint32_t sec=min(displaySec,ntpSec);bool timerEnabled=sec!=UINT32_MAX;bool refreshOnWake=timerEnabled&&displaySec<=ntpSec;timeval now;gettimeofday(&now,nullptr);rtcWakeEpochUs=timeOK()?((int64_t)now.tv_sec*1000000LL+now.tv_usec):0;rtcPlannedSleepUs=timerEnabled?(int64_t)sec*1000000LL:0;rtcMagic=RTC_MAGIC;rtcSaverVisible=saver;esp_sleep_disable_wakeup_source(ESP_SLEEP_WAKEUP_ALL);gpio_wakeup_enable((gpio_num_t)BTN_PIN,GPIO_INTR_LOW_LEVEL);esp_sleep_enable_gpio_wakeup();if(timerEnabled)esp_sleep_enable_timer_wakeup((uint64_t)rtcPlannedSleepUs);display.hibernate();esp_light_sleep_start();esp_sleep_wakeup_cause_t cause=esp_sleep_get_wakeup_cause();display.init(115200,false,2,false);if(cause==ESP_SLEEP_WAKEUP_GPIO){saver=false;rtcSaverVisible=false;if(clockSleep){view=CLOCK;focus=true;}else{view=HOME;focus=false;}ignoreWakeButton=true;refreshPolicy.all();dirty=true;touched=millis();}else if(cause==ESP_SLEEP_WAKEUP_TIMER){if(refreshOnWake){if(clockSleep){view=CLOCK;focus=false;saver=false;refreshRegion(0,28,200,160,true);}else if(saver&&cfg.saverClockMin)refreshRegion(126,168,72,30,true);}wakeAfterRender=true;}}
void minuteRefresh(){uint32_t minute=timeOK()?localEpoch()/60:0;if(!minute||minute==lastMinute)return;lastMinute=minute;if(saver){if(cfg.saverClockMin&&minute%cfg.saverClockMin==0)refreshRegion(126,168,72,30,true);return;}if(view==HOME){refreshRegion(0,0,200,23,true);return;}if(view==CLOCK){tm n;if(local(n)&&lastClockDay!=n.tm_yday){refreshPolicy.all();dirty=true;}else refreshRegion(focus?0:0,focus?35:28,focus?200:100,focus?90:145,true);}}
void idle(){if(toastText.length())return;uint32_t now=millis();minuteRefresh();if(radio==OFF&&hourlySyncDue()){bool resume=wakeAfterRender;wakeAfterRender=false;beginHourlySync(resume);}if(autoScroll&&now-lastScroll>=cfg.scrollSec*1000UL){lastScroll=now;bool moved=false;if(view==BOOK||(view==API&&remote==MARKDOWN))moved=md.scrollDown(160);else if(view==API&&remote==TEXT&&remoteTextMore){rscroll+=160;moved=true;}if(moved){refreshPolicy.all();dirty=true;}else{autoScroll=false;showToast("Auto-scroll finished");}}if(focus&&!saver&&(view==HOME||view==LIST||view==CLOCK||view==SETTINGS)&&now-touched>=cfg.unfocus*1000UL){focus=false;refreshPolicy.all();dirty=true;}if(radio!=OFF||autoScroll)return;if(view==HOME&&!saver&&now-touched>=cfg.saverSec*1000UL){if(cfg.saver){chooseSaver();saver=true;refreshPolicy.all();render(false);sleepNow(cfg.saverClockMin>0);}else sleepNow(false);}else if(view!=HOME&&!saver&&now-touched>=30000){sleepNow(view==CLOCK&&!focus);}}
void setup(){setCpuFrequencyMhz(80);Serial.begin(115200);pinMode(BTN_PIN,INPUT_PULLUP);esp_sleep_wakeup_cause_t wake=esp_sleep_get_wakeup_cause();bool rtcStateValid=rtcMagic==RTC_MAGIC;bool savedSaver=rtcStateValid&&rtcSaverVisible;if(!rtcStateValid){rtcWakeEpochUs=0;rtcPlannedSleepUs=0;lastNtpAttemptHour=UINT32_MAX;lastNtpSuccessHour=UINT32_MAX;rtcSaverVisible=false;}pref.begin("ereader",false);bool resumeOtaWeb=pref.getBool("ota_resume",false);if(resumeOtaWeb)pref.remove("ota_resume");loadCfg();bool fsReady=LittleFS.begin(false);if(!fsReady)error("LittleFS mount failed");display.init(115200,false,2,false);md.begin();routes();if(wake==ESP_SLEEP_WAKEUP_TIMER&&rtcStateValid&&rtcWakeEpochUs>1704067200000000LL){int64_t restored=rtcWakeEpochUs+rtcPlannedSleepUs;timeval tv={(time_t)(restored/1000000LL),(suseconds_t)(restored%1000000LL)};settimeofday(&tv,nullptr);}if(fsReady){recoverStagedFiles();ensureExamples();}collectBooks();touched=millis();if(wake==ESP_SLEEP_WAKEUP_TIMER&&savedSaver){saver=true;render(false);sleepNow(true);}if(savedSaver&&wake!=ESP_SLEEP_WAKEUP_TIMER){saver=false;rtcSaverVisible=false;view=HOME;focus=false;dirty=true;}render(true);if(resumeOtaWeb)startWifi(true);else if(!timeOK()&&wake==ESP_SLEEP_WAKEUP_UNDEFINED)startWifi(false);}
void loop(){buttonLoop();radioLoop();if(webOn&&radio!=OFF)web.handleClient();if(wifiApplyAt&&(int32_t)(millis()-wifiApplyAt)>=0){wifiApplyAt=0;dns.stop();WiFi.softAPdisconnect(true);startWifi(true,false,true);}otaLoop();toastLoop();idle();if(dirty)render();if(wakeAfterRender&&radio==OFF){wakeAfterRender=false;sleepNow(true);}if(rebootAt&&millis()>=rebootAt)ESP.restart();delay(radio==OFF?8:2);}
