#pragma once

#include <Arduino.h>

constexpr char kWebPage[] PROGMEM = R"HTML(
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="#202124">
  <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect x='9' y='3' width='46' height='58' rx='6' fill='black'/%3E%3Crect x='13' y='8' width='38' height='43' rx='3' fill='white'/%3E%3Cpath d='M32 15C26 23 22 28 22 34a10 10 0 1020 0c0-6-4-11-10-19Z' fill='black'/%3E%3Cpath d='M27 36c2 3 5 4 8 2' fill='none' stroke='white' stroke-width='2' stroke-linecap='round'/%3E%3C/svg%3E">
  <title>InkPocket</title>
  <style>
    :root{--ink:#202124;--muted:#667085;--line:#d9dde5;--paper:#f4f6fa;--card:#fff;--accent:#3457d5;--accent2:#e9eeff;--danger:#b3261e;--ok:#137333}
    *{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.45 system-ui,-apple-system,Segoe UI,sans-serif}
    .topbar{position:sticky;top:0;z-index:5;display:flex;align-items:center;justify-content:space-between;padding:14px max(18px,calc((100% - 1040px)/2));background:#202124;color:#fff;box-shadow:0 2px 10px #0003}
    .brand{display:flex;align-items:center;gap:11px;font-size:19px;font-weight:700}.mark{display:block;width:34px;height:34px;flex:0 0 34px}
    .badge{padding:5px 10px;border-radius:99px;background:#ffffff20;font-size:12px}.badge.ok{background:#d7f4df;color:#0b5425}.badge.bad{background:#ffd9d6;color:#7e160f}
    main{max-width:1040px;margin:auto;padding:24px}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:18px}.metric,.card{background:var(--card);border:1px solid var(--line);border-radius:18px;box-shadow:0 2px 8px #1820440a}
    .metric{padding:14px 16px;min-width:0}.metric small{display:block;color:var(--muted);margin-bottom:3px}.metric strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
    .layout{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(280px,.8fr);gap:18px;align-items:start}.stack{display:grid;gap:18px;align-content:start}.card{padding:20px}.card h2{font-size:18px;margin:0}.cardhead{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:16px}.subtle{color:var(--muted);font-size:13px}
    button,.button,input{font:inherit}button,.button{border:0;border-radius:11px;padding:10px 14px;background:var(--accent);color:#fff;font-weight:650;cursor:pointer;text-decoration:none;text-align:center}button.ghost,.button.ghost{background:var(--accent2);color:#233c9e}button.danger{background:#fde7e5;color:var(--danger)}button:disabled{opacity:.5;cursor:wait}
    input[type=text],input[type=password],input[type=file]{width:100%;border:1px solid var(--line);border-radius:11px;background:#fff;padding:11px 12px;outline:none}input[type=file]{padding:6px}input[type=file]::file-selector-button{border:0;border-radius:8px;padding:7px 10px;margin-right:9px;background:var(--accent2);color:#233c9e;font-weight:650;cursor:pointer}input:focus{border-color:var(--accent);box-shadow:0 0 0 3px #3457d522}
    .drop{display:grid;place-items:center;gap:7px;min-height:126px;padding:20px;border:2px dashed #a7afbe;border-radius:14px;background:#fafbfe;text-align:center;cursor:pointer}.drop.drag{border-color:var(--accent);background:var(--accent2)}.drop strong{font-size:16px}.drop input{display:none}
    .progress{margin-top:13px}.progress[hidden]{display:none}.track{height:10px;overflow:hidden;border-radius:99px;background:#e3e7ee}.fill{height:100%;width:0;background:var(--accent);transition:width .16s linear}.progressline{display:flex;justify-content:space-between;gap:10px;margin-top:6px;color:var(--muted);font-size:12px}
    .storage{margin:13px 0 4px}.files{display:grid;gap:8px;margin-top:14px}.empty{padding:25px;border:1px dashed var(--line);border-radius:12px;color:var(--muted);text-align:center}.file{display:grid;grid-template-columns:34px minmax(0,1fr) auto;align-items:center;gap:10px;padding:10px;border:1px solid var(--line);border-radius:12px}.filetype{display:grid;place-items:center;width:34px;height:34px;border-radius:10px;background:var(--accent2);color:#233c9e;font-size:10px;font-weight:800}.filename{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:650}.filemeta{color:var(--muted);font-size:12px}.fileactions{display:flex;gap:6px}.fileactions button,.fileactions .button{padding:7px 9px;border-radius:9px;font-size:12px}
    .actions{display:grid;grid-template-columns:1fr 1fr;gap:9px}.fields{display:grid;gap:10px}.note{padding:10px 12px;border-radius:11px;background:#f2f4f7;color:var(--muted);font-size:13px}.message{min-height:20px;margin:10px 0 0;color:var(--muted);font-size:13px}.message.error{color:var(--danger)}.message.success{color:var(--ok)}
    @media(max-width:760px){main{padding:16px}.summary{grid-template-columns:1fr 1fr}.layout{grid-template-columns:1fr}.topbar{padding:12px 16px}.card{padding:16px}}
    @media(max-width:430px){.summary{grid-template-columns:1fr 1fr;gap:8px}.metric{padding:11px}.actions{grid-template-columns:1fr}.file{grid-template-columns:32px minmax(0,1fr)}.fileactions{grid-column:1/-1}.fileactions>*{flex:1}}
  </style>
</head>
<body>
  <header class="topbar"><div class="brand"><svg class="mark" viewBox="0 0 512 512" role="img" aria-label="InkPocket"><rect x="78" y="36" width="356" height="440" rx="44" fill="#fff"/><rect x="108" y="70" width="296" height="328" rx="20" fill="#202124"/><path d="M256 126c-48 65-76 105-76 145a76 76 0 1 0 152 0c0-40-28-80-76-145Z" fill="#fff"/><path d="M220 289c12 22 35 30 57 20" fill="none" stroke="#202124" stroke-width="14" stroke-linecap="round"/><rect x="184" y="423" width="144" height="18" rx="9" fill="#202124"/></svg>InkPocket</div><span id="connection" class="badge">Connecting</span></header>
  <main>
    <section class="summary" aria-label="Device status">
      <div class="metric"><small>Screen</small><strong id="app">—</strong></div>
      <div class="metric"><small>Device time</small><strong id="clock">—</strong></div>
      <div class="metric"><small>Address</small><strong id="ip">—</strong></div>
      <div class="metric"><small>Signal</small><strong id="signal">—</strong></div>
    </section>
    <div class="layout">
      <section class="card">
        <div class="cardhead"><div><h2>Library</h2><div class="subtle">Markdown, text, and 1-bit BMP files in LittleFS</div></div><button id="refresh" class="ghost">Refresh</button></div>
        <label id="drop" class="drop" for="libraryFile"><strong>Choose a file or drop it here</strong><span>.md/.txt up to 256 KiB · .bmp up to 7 KiB</span><input id="libraryFile" type="file" accept=".md,.txt,.bmp,text/markdown,text/plain,image/bmp"></label>
        <div id="fileProgress" class="progress" hidden><div class="track"><div class="fill"></div></div><div class="progressline"><span class="label">Waiting</span><span class="value">0%</span></div></div>
        <p id="fileStatus" class="message" aria-live="polite"></p>
        <div class="storage"><div class="track"><div id="storageFill" class="fill"></div></div><div class="progressline"><span>LittleFS storage</span><span id="storageText">—</span></div></div>
        <div id="fileList" class="files"><div class="empty">Loading files…</div></div>
      </section>
      <div class="stack">
        <section class="card"><div class="cardhead"><h2>Device</h2></div><div class="actions"><button data-app="home">Home</button><button data-app="reader">Reader</button><button data-app="clock">Clock</button><button data-app="settings">Settings</button><button id="sync" class="ghost">Sync time</button></div><p id="actionStatus" class="message" aria-live="polite"></p><div class="note">InkPocket turns Wi-Fi off 60 seconds after your last action. Background status checks do not keep the radio awake.</div></section>
        <section class="card"><div class="cardhead"><h2>Wi-Fi</h2></div><div class="fields"><input id="ssid" type="text" maxlength="32" autocomplete="off" placeholder="Network name (SSID)"><input id="password" type="password" maxlength="63" autocomplete="new-password" placeholder="Password"><button id="saveWifi">Save and connect</button></div><p id="wifiStatus" class="message" aria-live="polite"></p></section>
        <section class="card"><div class="cardhead"><div><h2>Firmware update</h2><div class="subtle">Install an InkPocket .bin file</div></div></div><div class="fields"><input id="firmware" type="file" accept=".bin,application/octet-stream"><button id="install">Install firmware</button></div><div id="otaProgress" class="progress" hidden><div class="track"><div class="fill"></div></div><div class="progressline"><span class="label">Waiting</span><span class="value">0%</span></div></div><p id="otaStatus" class="message" aria-live="polite"></p><div class="note">Keep the device powered. Its e-paper screen mirrors progress and it restarts only after verification succeeds.</div></section>
      </div>
    </div>
  </main>
  <script>
    'use strict';
    const $=selector=>document.querySelector(selector);
    const MAX_FILE=256*1024,MAX_BMP=7*1024;
    const bytes=value=>{if(value<1024)return value+' B';if(value<1048576)return(value/1024).toFixed(1)+' KiB';return(value/1048576).toFixed(1)+' MiB'};
    const setMessage=(selector,text,type='')=>{const node=$(selector);node.textContent=text;node.className='message '+type};
    function setProgress(selector,label,value){const box=$(selector),percent=Math.max(0,Math.min(100,Math.round(value)));box.hidden=false;box.querySelector('.fill').style.width=percent+'%';box.querySelector('.label').textContent=label;box.querySelector('.value').textContent=percent+'%'}
    async function request(url,options){const response=await fetch(url,options);const text=await response.text();if(!response.ok)throw Error(text||('Request failed: '+response.status));return text}
    function upload(url,field,file,onProgress){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest(),form=new FormData();form.append(field,file);xhr.open('POST',url);xhr.upload.onprogress=event=>{if(event.lengthComputable)onProgress(event.loaded/event.total*100)};xhr.upload.onload=()=>onProgress(100);xhr.onerror=()=>reject(Error('Connection lost during upload.'));xhr.onload=()=>xhr.status>=200&&xhr.status<300?resolve(xhr.responseText):reject(Error(xhr.responseText||('Upload failed: '+xhr.status)));xhr.send(form)})}
    function fileType(name){const extension=name.split('.').pop().toUpperCase();return extension==='MARKDOWN'?'MD':extension.slice(0,4)}
    function renderFiles(data){const list=$('#fileList');list.replaceChildren();const usage=data.total?data.used/data.total*100:0;$('#storageFill').style.width=Math.min(100,usage)+'%';$('#storageText').textContent=bytes(data.used)+' / '+bytes(data.total);if(!data.files.length){const empty=document.createElement('div');empty.className='empty';empty.textContent='LittleFS has no readable files.';list.append(empty);return}data.files.forEach(item=>{const row=document.createElement('div');row.className='file';const type=document.createElement('div');type.className='filetype';type.textContent=fileType(item.name);const details=document.createElement('div');const name=document.createElement('div');name.className='filename';name.textContent=item.name.replace(/^\//,'');const meta=document.createElement('div');meta.className='filemeta';meta.textContent=bytes(item.size);details.append(name,meta);const actions=document.createElement('div');actions.className='fileactions';const open=document.createElement('a');open.className='button ghost';open.textContent='Open';open.target='_blank';open.rel='noopener';open.href='/api/files/download?path='+encodeURIComponent(item.name);const remove=document.createElement('button');remove.className='danger';remove.textContent='Delete';remove.onclick=()=>deleteFile(item.name);actions.append(open,remove);row.append(type,details,actions);list.append(row)})}
    async function refresh(passive=false){try{const suffix=passive?'?passive=1':'';const [statusText,filesText]=await Promise.all([request('/api/v1/status'+suffix),request('/api/files'+suffix)]);const status=JSON.parse(statusText),files=JSON.parse(filesText);$('#connection').textContent=status.wifi==='connected'?'Online':status.wifi;$('#connection').className='badge '+(status.wifi==='connected'?'ok':'');$('#app').textContent=status.app;$('#clock').textContent=status.time;$('#ip').textContent=status.ip;$('#signal').textContent=status.wifi==='connected'?status.rssi+' dBm':'—';renderFiles(files)}catch(error){$('#connection').textContent='Offline';$('#connection').className='badge bad';setMessage('#fileStatus',error.message,'error')}}
    function validateLibrary(file){if(!file)throw Error('Choose a file first.');const name=file.name.toLowerCase(),isBmp=name.endsWith('.bmp');if(!isBmp&&!name.endsWith('.md')&&!name.endsWith('.txt'))throw Error('Only .md, .txt, and .bmp files are accepted.');if(!file.size)throw Error('The selected file is empty.');if(file.size>(isBmp?MAX_BMP:MAX_FILE))throw Error(isBmp?'BMP files must be 7 KiB or smaller.':'Text files must be 256 KiB or smaller.');return file}
    async function uploadLibrary(file){try{validateLibrary(file);setMessage('#fileStatus','Uploading '+file.name+'…');setProgress('#fileProgress','Uploading',0);await upload('/api/files/upload','file',file,value=>setProgress('#fileProgress',value===100?'Finalising':'Uploading',value));setProgress('#fileProgress','Complete',100);setMessage('#fileStatus','Upload complete.','success');await refresh()}catch(error){setMessage('#fileStatus',error.message,'error')}}
    async function deleteFile(path){if(!confirm('Delete '+path.replace(/^\//,'')+'?'))return;try{await request('/api/files/delete?path='+encodeURIComponent(path),{method:'POST'});setMessage('#fileStatus','File deleted.','success');await refresh()}catch(error){setMessage('#fileStatus',error.message,'error')}}
    async function deviceAction(path,message){try{setMessage('#actionStatus',message+'…');await request(path,{method:'POST'});setMessage('#actionStatus',message+' requested.','success');setTimeout(refresh,500)}catch(error){setMessage('#actionStatus',error.message,'error')}}
    async function saveWifi(){const ssid=$('#ssid').value.trim(),password=$('#password').value;if(!ssid){setMessage('#wifiStatus','Enter a network name.','error');return}if(ssid.length>32||password.length>63){setMessage('#wifiStatus','SSID or password is too long.','error');return}try{setMessage('#wifiStatus','Saving…');await request('/api/wifi',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'ssid='+encodeURIComponent(ssid)+'&password='+encodeURIComponent(password)});setMessage('#wifiStatus','Saved. The device is reconnecting.','success')}catch(error){setMessage('#wifiStatus',error.message,'error')}}
    async function waitForRestart(){for(let attempt=0;attempt<30;attempt++){await new Promise(resolve=>setTimeout(resolve,1500));try{await request('/api/v1/status');setMessage('#otaStatus','Update complete. InkPocket is back online.','success');setProgress('#otaProgress','Complete',100);await refresh();return}catch(error){}}setMessage('#otaStatus','Installed. Reconnect to InkPocket if this page does not recover.','success')}
    async function installFirmware(){const file=$('#firmware').files[0],button=$('#install');if(!file){setMessage('#otaStatus','Choose a .bin firmware file first.','error');return}if(!file.name.toLowerCase().endsWith('.bin')||!file.size){setMessage('#otaStatus','Choose a non-empty .bin firmware file.','error');return}button.disabled=true;try{setMessage('#otaStatus','Uploading firmware. Keep power connected.');setProgress('#otaProgress','Uploading',0);await upload('/api/ota?size='+file.size,'firmware',file,value=>setProgress('#otaProgress',value===100?'Verifying on device':'Uploading',value));setMessage('#otaStatus','Firmware verified. InkPocket is restarting…','success');setProgress('#otaProgress','Restarting',100);waitForRestart()}catch(error){button.disabled=false;setMessage('#otaStatus',error.message,'error')}}
    $('#refresh').onclick=refresh;$('#sync').onclick=()=>deviceAction('/api/v1/time/sync','Time sync');document.querySelectorAll('[data-app]').forEach(button=>button.onclick=()=>deviceAction('/api/v1/app?name='+button.dataset.app,'Open '+button.textContent));$('#saveWifi').onclick=saveWifi;$('#install').onclick=installFirmware;$('#libraryFile').onchange=event=>uploadLibrary(event.target.files[0]);
    const drop=$('#drop');['dragenter','dragover'].forEach(name=>drop.addEventListener(name,event=>{event.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(name=>drop.addEventListener(name,event=>{event.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',event=>uploadLibrary(event.dataTransfer.files[0]));
    refresh();setInterval(()=>refresh(true),15000);
  </script>
</body>
</html>
)HTML";
